version: "3.9"

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thinkbiz-hitl-gateway
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      MONGODB_DB_NAME: ${MONGODB_DB_NAME:-hitl}
      MONGODB_OPERATORS_COLLECTION: ${MONGODB_OPERATORS_COLLECTION:-operators}
    restart: unless-stopped

  # Το Frontend UI
  agent-ui:
    build:
      context: .
      dockerfile: Dockerfile
      target: agent-ui # <--- Εδώ διαλέγει το άλλο stage
    container_name: thinkbiz-hitl-ui
    ports:
      - "8501:8501"
    environment:
      - GATEWAY_URL=http://gateway:8000/api/v1/hitl-request
    restart: unless-stopped
    depends_on:
      - gateway
